# GitHub Actions workflow to create an Expo/Android Development Build with EAS.
# https://github.com/expo/expo-github-action
#

name: Android App Development Build

on:
  workflow_dispatch: # allows manual triggering of the workflow from the GitHub Actions tab.
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup repo
        uses: actions/checkout@v4 # checks out the repository to the runner

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'yarn'

      - name: Set up Java Development Kit (JDK)
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'oracle'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest # EAS CLI version
          token: ${{ secrets.EXPO_TOKEN }} # uses a GitHub secret for Expo authentication.

      - name: Install dependencies
        run: yarn install

      - name: Build Android app
        run:
          eas build --platform android --profile development --local --output ${{ github.workspace }}/app-dev-build.apk

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-dev-release # name of the artifact to upload.
          path: ${{ github.workspace }}/app-dev-build.apk # what to upload.
          overwrite: true # artifact with a matching name will be deleted before a new one is uploaded.
          retention-days: 5
